import { type NextPage } from "next";
import Head from "next/head";
import { JsonForms } from "@jsonforms/react";
import { vanillaCells, vanillaRenderers } from "@jsonforms/vanilla-renderers";

const initialData = {
  doop: "John Doe"
};

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Form test</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <JsonForms
          data={initialData}
          schema={schema}
          uischema={uischema}
          renderers={vanillaRenderers}
          cells={vanillaCells}
        />
      </main>
    </>
  );
};

export default Home;

const schema = {
  type: "object",
  properties: {
    doop: {
      type: "string",
      minLength: 3,
      description: "Please enter your name",
    },
  },
};

const uischema = {
  type: "VerticalLayout",
  elements: [
    {
      type: "Label",
      text: "Additional Information",
    },
    {
      type: "Control",
      scope: "#/properties/doop",
    }
  ],
};
